### ISSUE TITLE
Config File For reproducing experiments

### ISSUE THREAD

**Issue by ThakurSarveshGit** [mbanani/unsupervisedRR#4]
Hi,

I could not locate the configuration files used for the training part. I want to train the network on scannet dataset. Can you please point to where I can find config files.

Thanks and regards,
Sarvesh

**Comment by mbanani** [comment]
Hi Thakur, sorry for missing your issue earlier. The configs used to train the model are the default configs. So you can use the debug config [unsupervisedRR/configs/debug.yaml](https://github.com/mbanani/unsupervisedRR/blob/main/unsupervisedRR/configs/debug.yaml) to run the experiments. Hopefully this clarifies the issue.
