### ISSUE TITLE
Could you please give me training instructions

### ISSUE THREAD

**Issue by linxcan** [mbanani/unsupervisedRR#6]
Hello！Thank you for your work. I am very interested in your work. Could you please give me training instructions? I want to try to train. Thank you very much.

**Comment by mbanani** [comment]
Hi @linxcan,

Thank you for your interest and sorry I never updated the train docs. The config defaults should be the same one as the main experiment. So running the following command should work once you set up the environment and dataset appropriately. To train a base model on ScanNet, you can just use the `debug.yaml` config as follows:

```
python train.py train debug.yaml
```

You could define experiment groups in folder with modification configs, check this portion of the code: 
https://github.com/mbanani/unsupervisedRR/blob/4ba5b1cc76080f5c6fd99cec155453f43b547bcd/train.py#L36-L40

If you are interested in unsupervised registration, I would suggest checking my follow-up work [byoc](https://github.com/mbanani/byoc) which builds on this work and simplifies it by removing the rendering component and achieving better performance. If you're interested in learning visual features, you should use the [vis_byoc](https://github.com/mbanani/byoc/blob/main/byoc/configs/experiment/vis_byoc.yaml) config. You should also check issue #5 for some tips and tricks to improve performance. 

Please let me know if you have any other questions.

**Comment by linxcan** [comment]
Thank you for your reply. It helps me a lot.
