### ISSUE TITLE
Whether the calculated Rt is differentiable

### ISSUE THREAD

**Issue by linxcan** [mbanani/unsupervisedRR#7]
Hello, I observed on your code that when Rt is calculated according to the point correspondence, it is solved by SVD. But is the loss obtained in this way derivable?
![image](https://user-images.githubusercontent.com/91445884/206620132-764deca4-3223-4deb-a8ef-4066a0c057d3.png)

https://github.com/mbanani/unsupervisedRR/blob/4ba5b1cc76080f5c6fd99cec155453f43b547bcd/unsupervisedRR/models/alignment.py#L127

**Comment by mbanani** [comment]
Hi @linxcan, 

PyTorch's implementation of SVD is differentiable, as seen [here](https://pytorch.org/docs/stable/generated/torch.svd.html), allowing us to define losses using the estimated Rt and back propagating the loss to the features.

**Comment by linxcan** [comment]
Thanks for your response!
